FROM ruby:3.0.1

# Install essential packages
RUN apt-get update && apt-get install -y \
    nodejs git python-setuptools \
    && apt-get clean \
    && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update && apt-get install yarn

WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
